const AROEIRA: Property = {
  id: 'casa-aroeira-itapororoca', code: 'TBA-285', name: { pt: 'Casa Aroeira — Itapororoca', en: 'Casa Aroeira — Itapororoca' },
  purpose: ['aluguel'], location: 'Praia de Itapororoca', suites: 6, guests: 12, baths: 6, area: 'Terreno 3.670 m² · 700 m² construídos',
  price: { pt: 'R$ 20.000 / diária', en: 'R$ 20,000 / night' },
  priceLow: { pt: 'R$ 17.000 / diária', en: 'R$ 17,000 / night' },
  carnaval: { pt: 'R$ 125.000 / pacote', en: 'R$ 125,000 / package' },
  reveillon: { pt: 'R$ 700.000 / pacote', en: 'R$ 700,000 / package' },
  image: '/img/aroeira/01.webp',
  gallery: ['/img/aroeira/01.webp','/img/aroeira/02.webp','/img/aroeira/03.webp','/img/aroeira/04.webp','/img/aroeira/05.webp','/img/aroeira/06.webp','/img/aroeira/07.webp','/img/aroeira/08.webp','/img/aroeira/09.webp','/img/aroeira/10.webp','/img/aroeira/11.webp','/img/aroeira/12.webp','/img/aroeira/13.webp','/img/aroeira/14.webp','/img/aroeira/15.webp','/img/aroeira/16.webp','/img/aroeira/17.webp','/img/aroeira/18.webp','/img/aroeira/19.webp','/img/aroeira/20.webp','/img/aroeira/21.webp','/img/aroeira/22.webp','/img/aroeira/23.webp','/img/aroeira/24.webp','/img/aroeira/25.webp','/img/aroeira/26.webp','/img/aroeira/27.webp','/img/aroeira/28.webp','/img/aroeira/29.webp','/img/aroeira/30.webp','/img/aroeira/31.webp','/img/aroeira/32.webp','/img/aroeira/33.webp','/img/aroeira/34.webp','/img/aroeira/35.webp','/img/aroeira/36.webp','/img/aroeira/37.webp','/img/aroeira/38.webp','/img/aroeira/39.webp','/img/aroeira/40.webp','/img/aroeira/41.webp','/img/aroeira/42.webp','/img/aroeira/43.webp','/img/aroeira/44.webp','/img/aroeira/45.webp','/img/aroeira/46.webp','/img/aroeira/47.webp','/img/aroeira/48.webp','/img/aroeira/49.webp','/img/aroeira/50.webp'], featured: false,
  amenities: {
    pt: ['Pé na areia', 'Vista para o mar', 'Piscina', 'Apoio de praia', 'Espaço gourmet', 'Churrasqueira', 'Cozinha equipada', 'Adega de vinhos', 'Cervejeira', 'Sala de estar', 'Sala de jantar', 'Sala de TV', 'Lavabo', 'Lavanderia', 'Máquina de lavar-louça', 'Máquina de gelo', 'Freezer', 'Cofres nos quartos', 'Mosquiteiro', 'Ar-condicionado', 'Ventilador de teto', 'Internet Wi-Fi', 'TV a cabo, Sky e Netflix', 'Som ambiente e som para iPod', 'Kids friendly e kit bebê', 'Espreguiçadeiras e ombrelone', 'Estacionamento', 'Gerador', 'Poço artesiano', 'Extintor', 'Secador de cabelo', 'Roupas de cama, mesa e banho', 'Toalhas de praia e piscina'],
    en: ['Beachfront', 'Ocean view', 'Swimming pool', 'Beach service', 'Gourmet area', 'Barbecue', 'Equipped kitchen', 'Wine cellar', 'Beer fridge', 'Living room', 'Dining room', 'TV room', 'Powder room', 'Laundry', 'Dishwasher', 'Ice maker', 'Freezer', 'In-room safes', 'Mosquito nets', 'Air conditioning', 'Ceiling fans', 'Wi-Fi internet', 'Cable TV, Sky and Netflix', 'Ambient sound and iPod dock', 'Kids friendly and baby kit', 'Sun loungers and parasol', 'Parking', 'Generator', 'Artesian well', 'Fire extinguisher', 'Hairdryer', 'Bed, table and bath linens', 'Beach and pool towels'],
  },
  description: {
    pt: 'Implantada em um terreno de 3.670 m², a Casa Aroeira conta com 700 m² de área construída e acomoda até 12 hóspedes em 6 suítes confortáveis, distribuídas de forma a garantir privacidade e bem-estar.\n\nOs ambientes sociais foram projetados para valorizar a integração entre interior e exterior. A sala principal se abre para o jardim e para a área da piscina, criando espaços acolhedores para convivência ao longo do dia. A ampla varanda acompanha toda a área social e oferece diferentes ambientes para descanso e refeições ao ar livre.\n\nNo piso superior, as suítes dispõem de varandas privativas e vista aberta para o mar, proporcionando ainda mais exclusividade à experiência de hospedagem.\n\nAlém da localização privilegiada à beira-mar, a propriedade está a aproximadamente 10 minutos de carro do Quadrado de Trancoso, permitindo fácil acesso aos restaurantes, lojas e ao charme do centro histórico da vila. Uma propriedade ideal para quem busca conforto, discrição e contato genuíno com um dos cenários mais desejados do litoral baiano.\n\nConfiguração das suítes: Suíte 01 (Master) com 1 cama de casal king size, ar-condicionado, mosquiteiro, closet, secador de cabelo e varanda com vista para o mar; Suíte 02 com 1 cama de casal king size, ar-condicionado, mosquiteiro, closet, secador de cabelo e varanda com vista para o mar; Suíte 03 com 2 camas de solteiro, ar-condicionado, mosquiteiro, closet, secador de cabelo e vista para o jardim; Suíte 04 com 1 cama de casal king size, ar-condicionado, closet, secador de cabelo e vista para o jardim; Suíte 05 com 2 camas de solteiro, ar-condicionado, closet, secador de cabelo e vista para o jardim; Suíte 06 com 1 cama de casal king size, ar-condicionado, mosquiteiro, closet, secador de cabelo e vista para o jardim. Capacidade para até 12 hóspedes.',
    en: 'Set on a 3,670 m² plot, Casa Aroeira offers 700 m² of built area and accommodates up to 12 guests in 6 comfortable suites, arranged to ensure privacy and well-being.\n\nThe social areas were designed to enhance the integration between indoors and outdoors. The main living room opens onto the garden and the pool area, creating welcoming spaces for gathering throughout the day. The wide veranda runs along the entire social area and offers different settings for relaxation and outdoor meals.\n\nUpstairs, the suites feature private verandas and open ocean views, adding even more exclusivity to the stay.\n\nBesides the privileged beachfront location, the property is approximately 10 minutes by car from Trancoso\'s Quadrado, with easy access to restaurants, shops and the charm of the village\'s historic center. An ideal property for those seeking comfort, discretion and a genuine connection with one of the most coveted settings on the Bahian coast.\n\nSuite layout: Suite 01 (Master) with 1 king-size bed, air conditioning, mosquito net, walk-in closet, hairdryer and veranda with ocean view; Suite 02 with 1 king-size bed, air conditioning, mosquito net, walk-in closet, hairdryer and veranda with ocean view; Suite 03 with 2 twin beds, air conditioning, mosquito net, closet, hairdryer and garden view; Suite 04 with 1 king-size bed, air conditioning, closet, hairdryer and garden view; Suite 05 with 2 twin beds, air conditioning, closet, hairdryer and garden view; Suite 06 with 1 king-size bed, air conditioning, mosquito net, closet, hairdryer and garden view. Capacity for up to 12 guests.',
  },
  staff: {
    pt: ['1 arrumadeira, 1 governanta, 1 cozinheira, 1 auxiliar de cozinha, 1 bartender e 1 caseiro'],
    en: ['1 housekeeper, 1 head housekeeper, 1 cook, 1 kitchen assistant, 1 bartender and 1 caretaker'],
  },
  notes: {
    pt: ['Locação mínima de 3 diárias.', 'Preços não incluem 10% de taxa de serviço.', 'Réveillon e Carnaval: valores de pacotes especiais.'],
    en: ['Minimum stay of 3 nights.', 'Rates do not include a 10% service charge.', 'New Year\'s Eve and Carnival: special package rates.'],
  },
  locationDetail: {
    pt: 'Estrada para Itaquena, Praia de Itapororoca — pé na areia, a aproximadamente 10 minutos de carro do Quadrado.',
    en: 'Estrada para Itaquena, Itapororoca Beach — beachfront, approximately 10 minutes by car from the Quadrado.',
  },
};
