const CASA11ALDEIA: Property = {
  id: 'aldeia-itapororoca-casa-11', code: 'TBA-284', name: { pt: 'Casa 11 — Aldeia Itapororoca', en: 'Casa 11 — Aldeia Itapororoca' },
  purpose: ['aluguel'], location: 'Praia de Itapororoca', suites: 7, guests: 14, baths: 7, area: '',
  price: { pt: 'R$ 22.000 / diária', en: 'R$ 22,000 / night' },
  priceLow: { pt: 'R$ 16.500 / diária', en: 'R$ 16,500 / night' },
  carnaval: { pt: 'Sob consulta', en: 'Upon request' },
  reveillon: { pt: 'R$ 605.000 / período', en: 'R$ 605,000 / period' },
  image: '/img/aldeia11/01.webp',
  gallery: ['/img/aldeia11/01.webp','/img/aldeia11/02.webp','/img/aldeia11/03.webp','/img/aldeia11/04.webp','/img/aldeia11/05.webp','/img/aldeia11/06.webp','/img/aldeia11/07.webp','/img/aldeia11/08.webp','/img/aldeia11/09.webp','/img/aldeia11/10.webp','/img/aldeia11/11.webp','/img/aldeia11/12.webp','/img/aldeia11/13.webp','/img/aldeia11/14.webp','/img/aldeia11/15.webp','/img/aldeia11/16.webp','/img/aldeia11/17.webp','/img/aldeia11/18.webp','/img/aldeia11/19.webp','/img/aldeia11/20.webp','/img/aldeia11/21.webp','/img/aldeia11/22.webp','/img/aldeia11/23.webp','/img/aldeia11/24.webp','/img/aldeia11/25.webp','/img/aldeia11/26.webp','/img/aldeia11/27.webp','/img/aldeia11/28.webp','/img/aldeia11/29.webp','/img/aldeia11/30.webp','/img/aldeia11/31.webp','/img/aldeia11/32.webp','/img/aldeia11/33.webp'], featured: false,
  amenities: {
    pt: ['Pé na areia', 'Vista para o mar', 'Condomínio fechado', 'Piscina privativa', 'Piscina do condomínio', 'Apoio de praia', 'Espaço gourmet', 'Cozinha equipada', 'Forno a lenha', 'Adega de vinhos', 'Carrinho de golfe (pickup)', 'Espreguiçadeiras e ombrelone', 'Sala de estar', 'Sala de jantar', 'Lavabo', 'Lavanderia', 'Máquina de gelo', 'Freezer', 'Frigobar', 'Ar-condicionado', 'Internet Wi-Fi', 'TV a cabo', 'Gerador', 'Estacionamento', 'Poço artesiano', 'Secador de cabelo', 'Roupas de cama, mesa e banho', 'Toalhas de praia e piscina', 'Serviços gerais'],
    en: ['Beachfront', 'Ocean view', 'Gated community', 'Private pool', 'Community pool', 'Beach service', 'Gourmet area', 'Equipped kitchen', 'Wood-fired oven', 'Wine cellar', 'Golf cart (pickup)', 'Sun loungers and parasol', 'Living room', 'Dining room', 'Powder room', 'Laundry', 'Ice maker', 'Freezer', 'Minibar', 'Air conditioning', 'Wi-Fi internet', 'Cable TV', 'Generator', 'Parking', 'Artesian well', 'Hairdryer', 'Bed, table and bath linens', 'Beach and pool towels', 'General services'],
  },
  description: {
    pt: 'À beira da Praia de Itapororoca, uma das mais belas de Trancoso, a Casa 11 Aldeia Itapororoca combina a arquitetura característica da região com ambientes amplos, acolhedores e totalmente integrados à natureza. Estruturas em madeira e vidro aproximam os espaços internos do jardim e do mar, enquanto a decoração, marcada por obras de artistas locais, traduz a identidade e a riqueza cultural do destino.\n\nA sala de estar valoriza o calor da madeira e os elementos naturais em cada detalhe. A propriedade dispõe de sete suítes confortáveis e de uma elegante sala de jantar, ampla e luminosa, conectada diretamente ao deck e à convidativa piscina.\n\nNa área externa, o paisagismo tropical envolve espaços pensados para a convivência. A cozinha e o forno a lenha criam o cenário ideal para almoços em família, encontros entre amigos e noites tranquilas sob o céu de Trancoso. O jardim arborizado oferece ainda diferentes ambientes de descanso, perfeitos para aproveitar o fim de tarde com privacidade e conforto.\n\nPé na areia e inserida em um condomínio fechado de alto padrão, a casa reúne localização privilegiada, serviço completo e uma atmosfera genuinamente trancosense.\n\nConfiguração das suítes: Suíte Master com 1 cama king-size, mosquiteiro, closet, ar-condicionado, TV, banheira e secador de cabelo; Suíte 02 com 1 cama king-size, mosquiteiro, ar-condicionado e secador de cabelo; Suítes 03 e 04 com 2 camas de solteiro conversíveis em cama de casal, mosquiteiro e ar-condicionado cada; Suíte 05 com 2 camas de solteiro conversíveis em cama de casal, 1 sofá-cama, mosquiteiro e ar-condicionado; Suíte 06 com 1 cama king-size, 1 sofá-cama de solteiro com bicama, mosquiteiro, closet e ar-condicionado; Suíte 07 com 1 cama king-size, mosquiteiro, ar-condicionado e banheira. Capacidade para até 14 hóspedes.',
    en: 'On the edge of Itapororoca Beach, one of the most beautiful in Trancoso, Casa 11 Aldeia Itapororoca combines the region\'s characteristic architecture with spacious, welcoming environments fully integrated into nature. Wood and glass structures bring the indoor spaces closer to the garden and the sea, while the décor, marked by works from local artists, reflects the identity and cultural richness of the destination.\n\nThe living room celebrates the warmth of wood and natural elements in every detail. The property offers seven comfortable suites and an elegant, bright dining room, connected directly to the deck and the inviting pool.\n\nOutside, tropical landscaping surrounds spaces designed for gathering. The kitchen and wood-fired oven create the perfect setting for family lunches, get-togethers with friends and quiet evenings under the Trancoso sky. The tree-filled garden also offers different resting areas, perfect for enjoying the late afternoon with privacy and comfort.\n\nBeachfront and set inside a high-end gated community, the house combines a privileged location, full service and a genuinely Trancoso atmosphere.\n\nSuite layout: Master Suite with 1 king-size bed, mosquito net, walk-in closet, air conditioning, TV, bathtub and hairdryer; Suite 02 with 1 king-size bed, mosquito net, air conditioning and hairdryer; Suites 03 and 04 with 2 twin beds convertible into a double, mosquito net and air conditioning each; Suite 05 with 2 twin beds convertible into a double, 1 sofa bed, mosquito net and air conditioning; Suite 06 with 1 king-size bed, 1 twin sofa bed with trundle, mosquito net, walk-in closet and air conditioning; Suite 07 with 1 king-size bed, mosquito net, air conditioning and bathtub. Capacity for up to 14 guests.',
  },
  staff: {
    pt: ['Equipe regular: 2 arrumadeiras, 1 cozinheira, 1 auxiliar de cozinha e 1 jardineiro/piscineiro', 'Equipe no Réveillon: 2 arrumadeiras, 1 cozinheira, 1 auxiliar de cozinha, 1 barman e 1 jardineiro/piscineiro'],
    en: ['Regular team: 2 housekeepers, 1 cook, 1 kitchen assistant and 1 gardener/pool attendant', 'New Year\'s Eve team: 2 housekeepers, 1 cook, 1 kitchen assistant, 1 bartender and 1 gardener/pool attendant'],
  },
  notes: {
    pt: ['Locação mínima de 4 diárias.', 'É permitida a hospedagem de animal de estimação de pequeno porte.', 'No Réveillon, deverá ser adicionada taxa de serviço de 5% ao valor da locação.'],
    en: ['Minimum stay of 4 nights.', 'Small pets are welcome.', 'A 5% service charge applies to New Year\'s Eve rentals.'],
  },
  locationDetail: {
    pt: 'Condomínio Aldeia de Itapororoca — pé na areia, a aproximadamente 15 minutos de carro do Quadrado.',
    en: 'Aldeia de Itapororoca gated community — beachfront, approximately 15 minutes by car from the Quadrado.',
  },
};
